
// <auto-generated />
using System.Collections.Immutable;
namespace Maestro.Events;

public static partial class AutoEventMapping {
    public static ImmutableDictionary<string, global::System.Type> IdsToEvents {get; private set;}

    static AutoEventMapping() {
        Initialize();
    }

    static partial void Initialize();
}
                