name: Main

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

permissions: write-all

jobs:
  test-apis:
    name: Test APIs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'
    - name: Test
      run: dotnet test src/Maestro.Web.Api.Tests/Maestro.Web.Api.Tests.csproj --verbosity normal --logger "trx;LogFileName=test-results.trx" || true
    - name: Report Test Results
      uses: dorny/test-reporter@v1
      with:
        name: Maestro.Web.Api.Tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        token: ${{ secrets.GITHUB_TOKEN }}
        

  plan-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::990455710365:role/github-actions-Role-4CtDOaS7TEJR
        aws-region: us-east-1
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'
    - name: Dotnet Restore
      run: dotnet restore src/Maestro.Deploy.Aws/Maestro.Deploy.Aws.csproj
    - name: Configure Lambda tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Publish Web
      run: dotnet lambda package -pl src/Maestro.Web/ -f net8.0 -c Release ./Maestro.Web.zip
    - name: Publish Event Handler
      run: dotnet lambda package -pl src/Maestro.Events.Runner/ -f net8.0 -c Release ./Maestro.Events.Runner.zip
    - name: Run Terraform CDK Plan
      uses: hashicorp/terraform-cdk-action@v1
      if: github.event.pull_request.merged != true && !(github.event_name == 'push' && github.ref == 'refs/heads/main')
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        Metadata__TmdbKey: ${{ secrets.TMDB_KEY }}      
      with:
        cdktfVersion: 0.19.2
        terraformVersion: 1.6.6
        mode: plan-only
        stackName: maestro-dotnet
        workingDirectory: ./src/Maestro.Deploy.Aws
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Terraform CDK Plan
      uses: hashicorp/terraform-cdk-action@v1
      if: github.event.pull_request.merged == true || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        Metadata__TmdbKey: ${{ secrets.TMDB_KEY }}      
      with:
        cdktfVersion: 0.19.2
        terraformVersion: 1.6.6
        mode: auto-approve-apply
        stackName: maestro-dotnet
        workingDirectory: ./src/Maestro.Deploy.Aws
        githubToken: ${{ secrets.GITHUB_TOKEN }}

