name: Main

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::990455710365:role/github-actions-Role-4CtDOaS7TEJR
        aws-region: us-east-1
    - name: AWS credentials test
      run: aws s3 ls s3://tfstate.omny.ca
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'
    - name: Restore dependencies
      run: dotnet restore src/MaestroMediaCenter.sln
    - name: Build
      run: dotnet build src/MaestroMediaCenter.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/MaestroMediaCenter.sln --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish src/MaestroMediaCenter.sln --configuration Release --output ./publish
    - name: zip
      run: cd publish && zip -r ../MaestroMediaCenter.zip ./
    - name: Run Terraform CDK Plan
      uses: hashicorp/terraform-cdk-action@v1
      if: github.event.pull_request.merged != true && !(github.event_name == 'push' && github.ref == 'refs/heads/main')
      with:
        cdktfVersion: 0.19.2
        terraformVersion: 1.6.6
        mode: plan-only
        stackName: maestro-dotnet
        workingDirectory: ./src/Maestro.Deploy.Aws
        terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Terraform CDK Plan
      uses: hashicorp/terraform-cdk-action@v1
      if: github.event.pull_request.merged == true || (github.event_name == 'push' && github.ref == 'refs/heads/main')
      with:
        cdktfVersion: 0.19.2
        terraformVersion: 1.6.6
        mode: auto-approve-apply
        stackName: maestro-dotnet
        workingDirectory: ./src/Maestro.Deploy.Aws
        terraformCloudToken: ${{ secrets.TF_API_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}

     